### PR TITLE
Add healthcheck command

### PR DESCRIPTION
**Pull request by simonklb**
This adds support for the new HEALTHCHECK instruction in Docker.

With this it's possible to check whether or not the workload running inside the container is working correctly. Should probably close https://github.com/juju-solutions/layer-docker/issues/54

### CODE REVIEW

**Comment by simonklb** [comment]
Sorry for the coveralls spam. Turns out JSONDecodeError doesn't exist in Python 3.4.

**Comment by lazypower** [comment]
Whoops, looks like this branch has collisions with the branch i just merged. Would you mind giving this a rebase and resubmitting @simonklb?

**Comment by simonklb** [comment]
Done!

**Review by marcoceppi — APPROVED** [review]
:+1: LGTM

**Comment by lazypower** [comment]
@simonklb Thanks for the contribution!

**Pull request merged**
