### PR TITLE
Adding travis CI config

### PR DESCRIPTION
**Pull request by lazypower**

### CODE REVIEW

**Comment by marcoceppi** [comment]
Don't you have to change the setup.py version for pypi to accept?

**Comment by lazypower** [comment]
Do you have a reference handy for me @marcoceppi?

**Comment by mbruzek** [comment]
+1 LGTM

**Comment by lazypower** [comment]
Actually, I'm not sure I understand what you're asking me @marcoceppi.
`version = "0.0.1"`,   is a valid version schema.  If we tag in juju-solutions/charms.docker, it should build on the tag and publish whatever is in setup.py.

**Comment by marcoceppi** [comment]
:boat:

**Pull request merged**
